export const ROLES = {
  FARMER: 'FARMER',
  GOVERNMENT: 'GOVERNMENT',
  PARTNER: 'PARTNER',
  SUPER_ADMIN: 'SUPER_ADMIN',
  OPERATIONS_ADMIN: 'OPERATIONS_ADMIN',
  VERIFICATION_ADMIN: 'VERIFICATION_ADMIN',
  FINANCE_ADMIN: 'FINANCE_ADMIN',
  PROJECT_ADMIN: 'PROJECT_ADMIN',
  CONTENT_ADMIN: 'CONTENT_ADMIN',
  SUPPORT_ADMIN: 'SUPPORT_ADMIN',
};

export const ROLE_LIST = Object.values(ROLES);

export const PERMISSIONS = {
  VIEW: 'view',
  CREATE: 'create',
  EDIT: 'edit',
  ASSIGN: 'assign',
  APPROVE: 'approve',
  REJECT: 'reject',
  QUERY: 'query',
  EXPORT: 'export',
  FINANCE_ACTION: 'finance_action',
  CONFIGURE: 'configure',
};

export const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  [ROLES.OPERATIONS_ADMIN]: [
    PERMISSIONS.VIEW,
    PERMISSIONS.CREATE,
    PERMISSIONS.EDIT,
    PERMISSIONS.ASSIGN,
    PERMISSIONS.APPROVE,
    PERMISSIONS.REJECT,
    PERMISSIONS.QUERY,
    PERMISSIONS.EXPORT,
  ],
  [ROLES.VERIFICATION_ADMIN]: [
    PERMISSIONS.VIEW,
    PERMISSIONS.APPROVE,
    PERMISSIONS.REJECT,
    PERMISSIONS.QUERY,
    PERMISSIONS.EXPORT,
  ],
  [ROLES.FINANCE_ADMIN]: [
    PERMISSIONS.VIEW,
    PERMISSIONS.FINANCE_ACTION,
    PERMISSIONS.EXPORT,
    PERMISSIONS.APPROVE,
  ],
  [ROLES.PROJECT_ADMIN]: [
    PERMISSIONS.VIEW,
    PERMISSIONS.CREATE,
    PERMISSIONS.EDIT,
    PERMISSIONS.ASSIGN,
    PERMISSIONS.EXPORT,
  ],
  [ROLES.CONTENT_ADMIN]: [
    PERMISSIONS.VIEW,
    PERMISSIONS.CREATE,
    PERMISSIONS.EDIT,
    PERMISSIONS.CONFIGURE,
  ],
  [ROLES.SUPPORT_ADMIN]: [
    PERMISSIONS.VIEW,
    PERMISSIONS.EDIT,
    PERMISSIONS.QUERY,
  ],
  [ROLES.FARMER]: [
    PERMISSIONS.VIEW,
    PERMISSIONS.CREATE,
    PERMISSIONS.EDIT,
  ],
  [ROLES.GOVERNMENT]: [
    PERMISSIONS.VIEW,
    PERMISSIONS.CREATE,
    PERMISSIONS.APPROVE,
    PERMISSIONS.EXPORT,
  ],
  [ROLES.PARTNER]: [
    PERMISSIONS.VIEW,
    PERMISSIONS.CREATE,
    PERMISSIONS.EDIT,
  ],
};
